---
name: Build and push docker images

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PLUGIN_NAME: ghcr.io/qosmio/docker-net-dhcp
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install script dependencies
        run: pip3 install -r scripts/requirements.txt

      - name: Generate build vars
        id: vars
        run: |
          SHA="${{ github.sha }}"
          echo "tag=${SHA:0:8}-$(date +%s)Z" >> $GITHUB_OUTPUT

      - name: Build
        run: make PLUGIN_TAG=${{ steps.vars.outputs.tag }} multiarch

      - name: Push
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
        run: |-
          make PLUGIN_TAG=${{ steps.vars.outputs.tag }} push-multiarch
          scripts/tag_multiarch_plugin.py -p "$PLATFORMS" "$PLUGIN_NAME:${{ steps.vars.outputs.tag }}" latest
