on:

  workflow_dispatch:
  repository_dispatch:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ghcr.io/qosmio/docker-net-dhcp
      PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install script dependencies
        run: pip3 install -r scripts/requirements.txt

      - name: Generate build vars
        id: vars
        run: |
          echo "version=$(echo "${{ github.ref }}" | sed -r 's|refs/tags/v(.+)|\1|')" >> $GITHUB_OUTPUT
          echo "Changelog: " > release.md
          git log --pretty=format:" - %s" "$(git describe --tags --abbrev=0 ${{ github.event.ref }}^)"..${{ github.event.ref }} >> release.md

      - name: Tag with release
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GH_TOKEN }}
        run: |
          scripts/tag_multiarch_plugin.py -p $PLATFORMS "$DOCKER_REPO:latest" release

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          #artifacts: "${{ github.event.repository.name }}-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
          name: docker-net-dhcp ${{ steps.vars.outputs.version }}
          bodyFile: release.md
